### ISSUE TITLE
Change partitioning step to allow partitioning according to vars

### ISSUE THREAD

**Issue by Geertsky** [Geertsky/ansible-install_initramfs#1]
Currently, the partitioning is done by tasks using `parted` and the partitioning is set statically in the tasks.
I want to change this to the `linux-system-roles/storage` role (https://github.com/linux-system-roles/storage) because it uses `blivet` and `blivet` is also used by kickstart.

A partitioning scheme defined in vars will look something like:

```
storage_pools:
        - name: primary_disk
          disks:
            - vda
          volumes:
           - name: boot
             size: "1 GiB"
             fs_type: xfs
             mount_point: "/boot"
           - name: efi
             size: "1 GiB"
             fs_type: vfat
             mount_point: "/boot/efi"
            - name: root
              size: "100 GiB"
              mount_point: "/"
              fs_type: xfs
              state: present
            - name: swap
              size: "40 GiB"
              fs_type: swap
```
